apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: istio-details-in
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/gauravkr19/istio.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: istio-details-img
spec:
  type: image
  params:
    - name: url
      value: gauravkr19/details:v1
