apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-docker-image-from-git-ratings-task-run
spec:
  serviceAccountName: dockerhub-service
  taskRef:
    name: build-docker-image-from-git-ratings
  params:
    - name: pathToDockerFile
      value: Dockerfile
  resources:
    inputs:
      - name: git-source
        resourceRef:
          name: istio-ratings-in
    outputs:
      - name: builtImage
        resourceRef:
          name: istio-ratings-img
