apiVersion: v1
kind: ServiceAccount
metadata:
  name: dockerhub-service
secrets:
  - name: dockercreds
---  
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: istio-mongodb-in
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/gauravkr19/istio.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: istio-mongodb-img
spec:
  type: image
  params:
    - name: url
      value: gauravkr19/mongodb:v1
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-image-from-git-mongodb
spec:
  params:
    - name: pathToDockerFile
      type: string
      description: The path to the dockerfile to build
      default: $(resources.inputs.git-source.path)/samples/bookinfo/src/mongodb/Dockerfile
    - name: pathToContext
      type: string
      description: |
        The build context used by Kaniko
        (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)        
      default: $(resources.inputs.git-source.path)/samples/bookinfo/src/mongodb/
  resources:
    inputs:
      - name: git-source
        type: git
    outputs:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.17.1
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.pathToDockerFile)
        - --destination=$(resources.outputs.builtImage.url)
        - --context=$(params.pathToContext)
